version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: urlshortener
      DB_USER: postgres
      DB_PASS: rootroot
      APP_BASE_URL: http://localhost:8080
    ports:
      - "8080:8080"
    restart: always

volumes:
  db_data:
